Issue308
jendrikseipp/vulture pull request #319
Opened 2023-08-19 02:40 UTC by whosayn

## Description

## Related Issue

## Checklist:

- [x] I have updated the documentation in the README.md file or my changes don't require an update.
- [x] I have added an entry in CHANGELOG.md.
- [x] I have added or adapted tests to cover my changes.
- [x] I have run `tox -e fix-style` to format my code and checked the result with `tox -e style`.

2023-08-19 07:17 UTC, jendrikseipp requested changes
Thanks for the PR! I like your enum refactoring! Once you've taken care of my small nitpicks, this can be merged.

2023-08-19 07:17 UTC, jendrikseipp commented on tests/test_script.py
> +from vulture.core import ExitCode
```suggestion
from vulture.utils import ExitCode
```

2023-08-19 07:17 UTC, jendrikseipp commented on vulture/core.py
> +        self.found_dead_code_or_error = ExitCode.NoDeadCode
```suggestion
        self.exit_code = ExitCode.NoDeadCode
```
Let's rename the variable.

2023-08-19 07:17 UTC, jendrikseipp commented on CHANGELOG.md
> +* Add dedicated exit code for when we find dead code
Start a new release section, and add your name or handle if you like:

```suggestion
# 2.9 (unreleased)
* Use exit code 3 when dead code is found (whosayn, #319).
```

2023-08-19 20:29 UTC, whosayn commented on vulture/core.py
> +        self.found_dead_code_or_error = ExitCode.NoDeadCode
I made the suggested changes. thanks!

2023-08-20 09:59 UTC, merged

2023-08-20 09:59 UTC, jendrikseipp commented
Thanks!