Read exclude patterns from .gitignore in absence of user-provided patterns (#344)
jendrikseipp/vulture pull request #345
Opened 2023-12-22 06:57 UTC by whosayn

## Description

Use .gitignore to exclude files if --exclude is missing from both
pyproject.toml and the command line. Vulture now requires the
pathspec library to run.

## Related Issue

#344 

## Checklist:

- [x] I have updated the documentation in the README.md file or my changes don't require an update.
- [x] I have added an entry in CHANGELOG.md.
- [x] I have added or adapted tests to cover my changes.
- [x] I have run `tox -e fix-style` to format my code and checked the result with `tox -e style`.

2023-12-22 22:07 UTC, jendrikseipp requested changes
Code looks great! After taking care of my nitpicks and fixing the CI checks, this is ready to be merged.

2023-12-22 22:07 UTC, jendrikseipp commented on README.md
> +Note that releases after 2.10 will parse the project's .gitignore files for
```suggestion
Vulture 2.11+ parses the `.gitignore` file in the current working directory for
```

2023-12-23 04:01 UTC, whosayn commented
@jendrikseipp a little stumped with the CI failures as I can't reproduce it locally. any ideas?

2023-12-23 16:26 UTC, jendrikseipp commented
Thanks for making the revisions! I fixed the CI error and everything looks good now :-)

2023-12-23 16:27 UTC, merged