Use ruff for linting
jendrikseipp/vulture pull request #347
Opened 2024-01-14 08:02 UTC by tqa236

## Description

Hello, 

This MR configures [ruff](https://github.com/astral-sh/ruff), an extremely fast Python linter and code formatter to `vulture`. `ruff` can potentially replace all the current linting and formatting tools, namely `black`, `flake8` and `pyupgrade`.

The current config in `pyproject.toml` is the default one, I put it there for ease of your review and customization. 

Let me know if this change is welcome. I can make further adjustments to the config to suit `vulture` style if needed.

## Checklist:

- [x ] I have updated the documentation in the README.md file or my changes don't require an update.
- [ ] I have added an entry in CHANGELOG.md.
- [ ] I have added or adapted tests to cover my changes.
- [ x] I have run `tox -e fix-style` to format my code and checked the result with `tox -e style`.

2024-01-15 10:58 UTC, jendrikseipp commented
Thanks for the PR! I like the proposed changes. In addition, can you make sure that we enable the same ruff tests as were enabled previously via the other tools? And then remove the other tools?

2024-01-15 20:00 UTC, tqa236 commented
Hi @jendrikseipp, this PR is ready for review.

There are a few things to consider:
- `ruff` can replace all existing linting packages. I have configured it to the same rules and removed the redundant packages.
- `ruff`  can even replace `black` with as a main formatter (some big packages like `pandas` already migrated, [ref](https://github.com/pandas-dev/pandas/pull/56704)). I can do this in the next PR if you think `vulture` can adopt this change. [This](https://docs.astral.sh/ruff/formatter/black/) is the documentation about the known deviations between `ruff` and `black`.
- I keep the current `tox -e style` and `tox -e fix-style` as the main entry points for now, but they can also be replaced completely with `pre-commit`. I do that in the next PR if you're ok with the deprecations of these `tox` commands.

2024-01-19 16:13 UTC, jendrikseipp requested changes
Thanks for revising the PR! I have a few more nitpicks, but I like where this is going :-)

I see the differences between ruff and black as an advantage for ruff. So if you like, it would be great if you could change the formatter to ruff in a separate PR later.

Also, feel free to replace the "tox -e style" and "tox -e fix-style" commands with pre-commit in another PR.

Great stuff!

2024-01-19 16:13 UTC, jendrikseipp commented on pyproject.toml
> +]
Can you keep only the excludes that are relevant for a typical Vulture checkout, please?

2024-01-19 16:13 UTC, jendrikseipp commented on pyproject.toml
> +select = ["E4", "E7", "E9", "F", "B", "C4", "UP", "W", "C901"]
Please add a comment telling which checks are enabled by ruff by default.

2024-01-19 16:13 UTC, jendrikseipp commented on pyproject.toml
> +  "C408",
```suggestion
  "C408",  # unnecessary dict call 
```

(use one line)

2024-01-19 16:13 UTC, jendrikseipp commented on pyproject.toml
> +select = ["E4", "E7", "E9", "F", "B", "C4", "UP", "W", "C901"]
Also, please add short comments on what these letters mean. For both of these changes, it's probably best to convert the list to have one entry per line, with a brief comment next to it.

2024-01-19 16:13 UTC, jendrikseipp commented on vulture/core.py
> +    def scavenge(self, paths, exclude=None):  # noqa: C901
Let's just remove C901 from the list of selected tests instead.

2024-01-19 16:13 UTC, jendrikseipp commented on tox.ini
>    bash
The bash special case is obsolete now. Same in the "style" part above.

2024-01-19 16:13 UTC, jendrikseipp commented on .github/workflows/pre-commit.yml
> +    - uses: actions/setup-python@v5
Is it necessary to set up a Python version here? The ubuntu-latest image already comes with Python installed.

2024-01-19 18:50 UTC, tqa236 commented
@jendrikseipp I updated the code according to your review. Can you take a look again, please? The list of patterns ignored by `ruff` now is a fuse of `.gitignore` and the one ignored by `black`.

Noted about the future improvement of `ruff format` and `pre-commit`, I can tackle them in follow-up PRs

2024-01-19 19:23 UTC, merged

2024-01-19 19:24 UTC, jendrikseipp commented
Great, thanks!

In an upcoming PR, please add a changelog entry for this and the other planned changes. And feel free to add your name or nick to the changelog entry.