Add -c/--config parameter to specify pyproject.toml path
jendrikseipp/vulture pull request #352
Opened 2024-03-12 15:48 UTC by glenrobertson

## Description
For projects that have a pyproject.toml config in a directory other than the root, this allows `vulture` to accept `--config path/to/pyproject.toml` (or `-c path/to/pyproject.toml`).

## Related Issue
No issue created or found.

## Checklist:

- [ ] I have updated the documentation in the README.md file or my changes don't require an update.
- [ ] I have added an entry in CHANGELOG.md.
- [ ] I have added or adapted tests to cover my changes.
- [ ] I have run `pre-commit run --all-files` to format and lint my code.

2024-03-12 15:49 UTC, glenrobertson commented
@jendrikseipp I'm curious if you agree with this change? I found it useful in my project. If so, I can finish this up and do the checklist items.
Thanks!

2024-03-13 10:25 UTC, jendrikseipp requested changes
Thanks for the PR! Yes, I like the suggested change.

2024-03-13 10:25 UTC, jendrikseipp commented on vulture/config.py
> +        help="Path to pyproject.toml config file",
```suggestion
        help="Path to pyproject.toml config file.",
```

2024-03-13 10:25 UTC, jendrikseipp commented on vulture/config.py
> +        "-c", "--config",
```suggestion
        "--config",
```
Let's be explicit here. This is also in line with ruff and black.

2024-03-15 08:30 UTC, jendrikseipp requested changes
Looks good! I only have two minor nitpicks.

2024-03-15 08:30 UTC, jendrikseipp commented on README.md
> +`vulture` will automatically look for a `pyproject.toml` in the current working directory.
```suggestion
Vulture will automatically look for a `pyproject.toml` in the current working directory.
```

2024-03-15 08:30 UTC, jendrikseipp commented on tests/test_config.py
> +import os
Can we use pathlib instead of os.path here?

2024-03-19 07:00 UTC, merged

2024-03-19 07:00 UTC, jendrikseipp commented
Thanks!